- name: start
  task: node --experimental-modules ./example/server/index.mjs

- name: format
  tasks: 
    - prettier --write '{src,tests}/**/*.{js,css}'
    - prettier --write '*.{js,json}'

- name: test
  tasks:
    - nyc ava
    - - eslint "src/**/**.js"

- name: test/coverage
  task: nyc report --reporter=text-lcov | coveralls
